### ISSUE TITLE
Where are the OpenCVWrapper.h？

### ISSUE THREAD

**Issue by mikeche6362** [adynathos/AugmentedUnreality#1]
Ｉdownload the OpenCV from opencv.org and its version is 2.4.13. When I installed it I can not find the OpencvWrapper.h. Why ?

**Comment by adynathos** [comment]
Please download the whole project here:
[AugmentedUnrealityProject_1_00.zip](https://googledrive.com/host/0B4QRvG9KRioDNG9RaGlpaTR4a2s/AugmentedUnrealityProject_1_00.zip)

It contains the right version of OpenCV and OpenCVWrapper - both with pre-built binaries.

The right OpenCVWrapper.h is created when you run the CMake build in opencv_wrapper. But you don't need to run the build - everything is contained in the download above.
