### ISSUE TITLE
support for Unreal Engine 4.17

### ISSUE THREAD

**Issue by Alolag** [adynathos/AugmentedUnreality#11]
Is their any support for Unreal Engine 4.17?

**Comment by ANURAGX** [comment]
For me this plugin is working fine, but haven't by tracking aruco or fiducial markers.
The most important thing is that it will compile successfully with UE 4.17.

**Comment by adynathos** [comment]
I did not try compiling it with 4.17 yet, I will let you know once i do.
The easiest way is to try and see if it builds or not.

Fiducial markers are tracked using OpenCV, so the changes in Unreal should have no effect on them.

**Comment by rubenalvesbcn** [comment]
I've tried to use the plugin with Unreal 4.17.2 on Linux but I had problems.
`dlopen failed: libopencv_ml.so.3.2: cannot open shared object file:`

I couldn't find this library: `find . -name ibopencv_ml.so.3.2`

I'll try to [compile OpenCV](https://github.com/adynathos/AugmentedUnreality/tree/master/ThirdParty/opencv) to see if it works.

**Comment by adynathos** [comment]
`libopencv_ml.so`

The `ml` module is not used in the plugin, so I wonder why it is referenced.
Maybe if I make a new build of OpenCV with the unused modules explicitly disabled, it will not be referenced. 
The included OpenCV build script should build just the needed modules.

**Comment by GameCreatures** [comment]
I'm currently trying to use it in 4.18 and I' also having  a lot of trouble.  fatal error: '../../../Core/Public/Android/AndroidApplication.h' file not found

**Comment by ANURAGX** [comment]
Replace that line with the below one, and the issue will be resolved.
#include "../../../ApplicationCore/Public/Android/Application.h"

**Comment by GameCreatures** [comment]
I changed that directory and now i'm getting a lot of this errors for each class. LogPlayLevel:   E:/Programs/AndroidWorks/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: C:/Users/AlexRivera/Documents/Unreal Projects/AugmentedUnrealityEx/Plugins/AugmentedUnreality/Binaries/Android/UE4-AugmentedUnreality-armv7-es2.a(Module.Aug
mentedUnreality.gen.cpp-armv7-es2.o): multiple definition of 'Z_Construct_UClass_UAURDriver()'

**Comment by ANURAGX** [comment]
Just clean your project .
Delete saved, intermediate and binaries folder and do the launch again.

This should fix his linking error.

**Comment by GameCreatures** [comment]
Thank you @ANURAGX for the help. I managed to compile it and it worked. Sadly I couldn't get it to work mixed with the Ar core plugin but still I'll be able to show my idea thanks to you.

**Comment by ANURAGX** [comment]
No problem man.

**Comment by adynathos** [comment]
I am working on a new build for the current UE.
Seems to be working so far, here is the preview download (currently binaries only for Win64).

Version <b>1.2.03</b> - updated for UE 4.18.2, OpenCV 3.4.0, gstreamer 1.12.4 - preview download:
<ul>
<li><a href="https://drive.switch.ch/index.php/s/uBl9W0YGqwBNSVR/download">Plugin</a></li>
<li><a href="https://drive.switch.ch/index.php/s/B6ipE0B9swAHroc/download">Example project</a></li>
</ul>

**Comment by jakwarne** [comment]
Hi adynathos, I have been trying the example project for 4.18.3

I had the same issue as 'GameCreatures' posted above.('../../../Core/Public/Android/AndroidApplication.h' file not found) 

If the answer is to change the line to (#include "../../../ApplicationCore/Public/Android/Application.h) 
where do I change this?

thanks

**Comment by adynathos** [comment]
Please try the new release <a href="https://github.com/adynathos/AugmentedUnreality/releases/tag/1.2.04">1.2.04</a> where this is fixed.

**Comment by jakwarne** [comment]
Ok, I will do that :) 

Thanks for replying so fast
