### ISSUE TITLE
Plugin building instructions

### ISSUE THREAD

**Issue by Firefly35** [adynathos/AugmentedUnreality#12]
Could you please provide inputs to build the plugin ?

I didn't find any information on the build process in the repository.

Thanks

**Comment by adynathos** [comment]
Unreal does that automatically:
<a href="https://github.com/adynathos/AugmentedUnreality#add-plugin-to-an-existing-project">Add the plugin to your project</a> and it will be built when you compile your project.

If you want to build the included OpenCV library from source, please see the <a href="https://github.com/adynathos/AugmentedUnreality/tree/master/ThirdParty/opencv">build instructions for modified OpenCV</a>.

**Comment by Firefly35** [comment]
Thanks a lot, I thought that once built, Unreal used the resulting plugin's binary using the plugin API.
I'm new to Unreal plugin development, sorry for the disturbance.

**Comment by adynathos** [comment]
> Thanks a lot, I thought that once built, Unreal used the resulting plugin's binary using the plugin API.

I think it does indeed do that. Since the binaries are included with the plugin, maybe it will not even rebuild.
But if you make some changes to the plugin source, Unreal will rebuild with your next project compilation.
