### ISSUE TITLE
Path does not start with a valid root.

### ISSUE THREAD

**Issue by Btje** [adynathos/AugmentedUnreality#14]
When trying to run the game on Android, the plugin won't work because of an invalid root. I'm using Android 6.0 and I've tried both the example project as my own custom project. I've included the full output log.
[WWAR.log](https://github.com/adynathos/AugmentedUnreality/files/1558752/WWAR.log)

**Comment by adynathos** [comment]
Maybe the plugin package is not declared in `*Build.cs`?
Could you show the `*Build.cs` files that you use?

**Comment by Btje** [comment]
I didn't change anything in the Build.cs, it's the one that is generated when you start a project, I'm not sure if there's a difference in Build.cs file between making a mobile project or a desktop one but it should not contain anything other than the default values.

**Comment by Btje** [comment]
Do I have a Build.cs file in a Blueprint only project?

**Comment by Btje** [comment]
I created an empty C++ file so it would generate the Build.cs file, I added the OpenCV declarations and the AugmentedUnreality decleration, it works now. I just have to figure out how to get the Android camera feed to the camera.

**Comment by adynathos** [comment]
Good to hear that it runs now.

> I just have to figure out how to get the Android camera feed to the camera.

Did the camera work?

**Comment by Btje** [comment]
Sadly I didn't have time to investigate any further, we only had 8 weeks
for that project including all the research and documentation. I switched
to Android Studio using the EasyAR library. I will probably check out your
project again sometime for personal projects.
