### ISSUE TITLE
Is there a build for UE4 - 4.18 ?

### ISSUE THREAD

**Issue by Pzy64** [adynathos/AugmentedUnreality#19]
This project didn't work on 4.17 or 4.18. Is there a way to make it run?.. Thanks for the amazing project!!

**Comment by adynathos** [comment]
You can try the version <b>1.2.03</b> - built for UE 4.18.2, OpenCV 3.4.0, gstreamer 1.12.4.
<ul>
<li><a href="https://drive.switch.ch/index.php/s/uBl9W0YGqwBNSVR/download">Plugin</a></li>
<li><a href="https://drive.switch.ch/index.php/s/B6ipE0B9swAHroc/download">Example project</a></li>
</ul>
Please let me know if it runs.
It does not yet have the binaries for Android/Linux but I can finish this if you need it.

**Comment by Pzy64** [comment]
I'm using UE4 4.18.1, 
I extracted plugin to /plugins/ folder.
[When I opened! I got an error](https://i.imgur.com/ll44LU8.png)
