### ISSUE TITLE
Hi,Adynathos.how to use AugmentedUnreality plugin on android device?

### ISSUE THREAD

**Issue by linqingwudiv1** [adynathos/AugmentedUnreality#2]
I hope you can tell me. How can I do？

**Comment by migero** [comment]
u add issues here not tutorials

**Comment by adynathos** [comment]
I made some progress towards Android, but it is not finished yet.
Right now the plugin can be built for Android and (sometimes) deployed to a device, but so far we did not manage to get the video from camera.

If you want to try, download the current development version:
- <a href="https://polybox.ethz.ch/index.php/s/eQ0H1X0dWHpy8IO/download">Plugin Only</a> (add to your existing project)
- <a href="https://polybox.ethz.ch/index.php/s/LhiEbHXRuqOTw4b/download">Example Project</a> (if you want a complete example)
and try deploying on a device.
You should try setting Android API level (in project settings) to 19 and if it crashes, to 21.

I will make a new version release when it works reliably on Android.

**Comment by linqingwudiv1** [comment]
@adynathos  thanks for your share,The Demo  is very helpful to my Project

**Comment by adynathos** [comment]
Version <a href="https://github.com/adynathos/AugmentedUnreality#downloads">1.2.0</a> allows the game to work on Android.
