### ISSUE TITLE
Fatal error: [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\Core\Private\GenericPlatform\GenericPlatformMemory.cpp] [Line: 183] Ran out of memory allocating 21873295360 bytes with alignment 0  

### ISSUE THREAD

**Issue by Pzy64** [adynathos/AugmentedUnreality#20]
`
Fatal error: [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\Core\Private\GenericPlatform\GenericPlatformMemory.cpp] [Line: 183] Ran out of memory allocating 21873295360 bytes with alignment 0

KERNELBASE
UE4Editor_ApplicationCore
UE4Editor_Core
UE4Editor_AugmentedUnreality!TArray<TScriptDelegate<FWeakObjectPtr>,TInlineAllocator<4,FDefaultAllocator> >::ResizeForCopy() [d:\program files\epic games\ue_4.18\engine\source\runtime\core\public\containers\array.h:2276]
UE4Editor_AugmentedUnreality!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [d:\program files\epic games\ue_4.18\engine\source\runtime\core\public\uobject\scriptdelegates.h:457]
UE4Editor_AugmentedUnreality!UE4Function_Private::TFunctionRefCaller<<lambda_fc10205e902d606e267dd2e3de1eb022>,void __cdecl(void)>::Call() [d:\program files\epic games\ue_4.18\engine\source\runtime\core\public\templates\function.h:245]
`

Error after launching Example project with plugin  1.2.03.

This error came when Launched project in Editor , No error with standalone Launch

**Comment by Pzy64** [comment]
I like to have android build of 1.2.03

**Comment by adynathos** [comment]
Hello,
Here is the build <a href="https://github.com/adynathos/AugmentedUnreality/releases/tag/1.2.04">1.2.04</a> for UE 4.19 and OpenCV 3.4.1
It contains the OpenCV libraries for Windows and Android.
