### ISSUE TITLE
Cannot launch on Android - UE 4.18, plugin v1.2.03

### ISSUE THREAD

**Issue by rebe1988** [adynathos/AugmentedUnreality#21]
Hi,
I'm trying to run the example project (v 1.2.03) on an android device.
When launching the app it gave me this error:

_impossible to find path "... \Plugins\AugmentedUnreality\ThirdParty\opencv\install\Android\sdk\native\3rdparty\libs\armeabi-v7a'."_

so I downloaded the OpenCV Android SDK from _https://github.com/opencv/opencv/releases/tag/3.2.0_ and I put the **sdk** folder into **"... \Plugins\AugmentedUnreality\ThirdParty\opencv\install\Android"**

Now, when building it gave me this error:

_fatal error: '../../../Core/Public/Android/AndroidApplication.h' file not found_

So, as suggested in this thread (_https://github.com/adynathos/AugmentedUnreality/issues/11_) I changed **Core** to **ApplicationCore** (line 21 of **AURVideoSourceAndroidCamera.cpp**)

Compilation was ok this time, but building the project failed again:

_no such file or directory: '... /AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_augmented_unreality.a'_

_no such file or directory: ... /Plugins/AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_aruco.a'_

So, I decided to try to rebuild OpenCV manually instead of using the downloaded SDK:
I deleted sdk from Install folder, downloaded **opencv-3.2.0** and **opencv_contrib-3.2.0**, put the content inside **... Plugins\AugmentedUnreality\ThirdParty\opencv\src** and then I run 

**python build.py build android --build_dir C:\AndroidOpenCV_Build**

Pyton script fails with this error: 

```
Task: build
- platform: android
- build directory: F:\TestBuild
- install directory: C:\...\Plugins\AugmentedUnreality\ThirdParty\opencv\install\Android
Running  CMake

Traceback (most recent call last):
  File "build.py", line 207, in <module>
    main()
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build.py", line 99, in build
    out_code = subprocess.call(cmd_cmake)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\...\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I don't know python and I have no idea of what is missing at this step. 
Any hint?

Thanks

**Comment by rebe1988** [comment]
Update:

I think the error is inside cmake.. i've seen that the command called from the python script is this one:

`cmake -C C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\cmake_settings\\android.cmake -DCMAKE_INSTALL_PREFIX=C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\install\\Android C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\src\\opencv`

I tried to run it manually from inside the build directory, but it ends with errors like these:

**Cannot find source file**
**F:/TestBuild/modules/features2d/opencv_features2d_pch.cpp**

**Cannot find source file**
**F:/TestBuild/modules/features2d/opencv_features2d_pch.cpp.cpp**

...

It's trying to load some source files from the build directory insted of the src one

**Comment by rebe1988** [comment]
Update:

I think the error is inside cmake.. i've seen that the command called from the python script is this one:
`
cmake -C C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\cmake_settings\\android.cmake -DCMAKE_INSTALL_PREFIX=C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\install\\Android C:\\...\\AugmentedUnrealityEx\\Plugins\\AugmentedUnreality\\ThirdParty\\opencv\\src\\opencv`

I tried to run it manually from inside the build directory, but it ends with errors like these:

**Cannot find source file
F:/TestBuild/modules/features2d/opencv_features2d_pch.cpp

Cannot find source file
F:/TestBuild/modules/features2d/opencv_features2d_pch.cpp.cpp**

...

It doesn't generate precompiled headers

**Comment by adynathos** [comment]
I usually build the android version of OpenCV on Linux, so I am not well acquainted with the process on Windows.
I will try to download the SDK and build it soon.

From building the Windows version of OpenCV, i remember that one should run the build script (and thus opencv) in a "visual studio console" (instead of the standard console)

**Comment by rebe1988** [comment]
Thanks... I found the reason:
In the readme there's still the link to OpenCV 3.2 instead of 3.4 (and i downloaded OpenCV sources from that link): that was causing a lot of warnings of deprecated functions and it was difficult to find the real cause.
The problem was that there was no "augmented unreality" module inside opencv_contrib src (i thought it was included in the plugin), so i downloaded it from your github and everything worked

**Comment by adynathos** [comment]
Ok, sorry for the wrong OpenCV version.
I have updated the info in the description:
https://github.com/adynathos/AugmentedUnreality/commit/2dd69f664d8c8a479a4c1a9c3e7399577c5f063d

**Comment by signupdemo** [comment]
ok.. so I followed the fixes, but Im stuck at this error, and cant seems to find these library files:

clang++.exe: error: no such file or directory:...AugmentedUnrealityEx/Plugins/AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_augmented_unreality.a'
UATHelper: Packaging (Android (ASTC)):   clang++.exe: error: no such file or directory: 
clang++.exe: error: no such file or directory:'...AugmentedUnrealityEx/Plugins/AugmentedUnreality/ThirdParty/opencv/install/Android/sdk/native/libs/armeabi-v7a/libopencv_aruco.a'
UATHelper: Packaging (Android (ASTC)):   ERROR: UBT ERROR: Failed to produce item: ....AugmentedUnrealityEx\Binaries\Android\AugmentedUnrealityEx-armv7-es2.so

**Comment by rebe1988** [comment]
Check if there is an "augmented unreality" folder inside opencv_contrib/modules

**Comment by signupdemo** [comment]
yes, there is.... and just to confirm, is this the right path for the opencv_contribe folder:
...AugmentedUnrealityEx\Plugins\AugmentedUnreality\ThirdParty\opencv\src\opencv_contrib\

**Comment by signupdemo** [comment]
adynathos just updated the missing libraries in 1.2.04... and it worked.
