### ISSUE TITLE
dll files are missing or built with it a different engine version

### ISSUE THREAD

**Issue by natarajnattu** [adynathos/AugmentedUnreality#27]
Hi Adynathos,

Im using 4.19, when im opening the Example project it is saying this error, pls help me out.

AugmentedUnrealityEx could not be compiled. Try rebuilding from source manually

**Comment by adynathos** [comment]
We don't know what the error is yet, the way to find out is to open the visual studio project and try to compile it.

**Comment by natarajnattu** [comment]
yes i did that and its working ... thanks for the reply @adynathos
