### ISSUE TITLE
How to know the status of the blueprint is being tracked or idle in the world

### ISSUE THREAD

**Issue by natarajnattu** [adynathos/AugmentedUnreality#29]
Hi adynathos,

  i am trying to hide the blueprints when ever the tracker is not finding in viewport.. is there any method to check the whether the blueprint is tracking state / idle state?

**Comment by zorderjohn** [comment]
Did you find out how to do it?

**Comment by adynathos** [comment]
This delegate should fire every time the pattern is detected.
https://github.com/adynathos/AugmentedUnreality/blob/master/Source/AugmentedUnreality/tracking/AURFiducialPattern.h#L31

Perhaps you can measure the time since the last detection.
