### ISSUE TITLE
UE 4.20 Support

### ISSUE THREAD

**Issue by peleglila** [adynathos/AugmentedUnreality#30]
Hi adynathos,

Your Plugin is awesome !
Will you be able to create a version supporting UE 4.20 ?

**Comment by adynathos** [comment]
Yes, i can fix the build problems for 4.20 next week - I'm on holiday until this Sunday.
 
Also 4.20 introduces some new AR related features which could be useful for the plugin. I don't have a plan to add that myself but I am open to collaborate.

**Comment by adynathos** [comment]
Addressed in 65d0b24e163541d25760735f6d8b9faf7b53ff41
