### ISSUE TITLE
support for Unreal Engine 4.16

### ISSUE THREAD

**Issue by RubyGemer** [adynathos/AugmentedUnreality#5]
Is their any support for Unreal Engine 4.16?
Also, I was using Unreal4AR but since it's paid I can't deploy to android & test my application. Can I develop an AR application with this plugin and deploy on my android phone?

**Comment by adynathos** [comment]
> Is their any support for Unreal Engine 4.16?

Ok, I made a version for 4.16, adjusting to changes in UnrealBuildTool C# classes
<a href="https://github.com/adynathos/AugmentedUnreality/releases/tag/1.2.02">Downloads</a>

> Can I develop an AR application with this plugin and deploy on my android phone?

Yes you can :)
